-- 017 — Require specific category emoji icons (no generic 🏷️ fallback)
-- Prerequisites: 015/016 (emoji_icon column)
-- 1) Backfill NULL / blank / generic tag with name-matched icons
-- 2) Enforce NOT NULL + non-empty + reject generic tag

ALTER TABLE categories
  ADD COLUMN IF NOT EXISTS emoji_icon TEXT;

-- Exact name matches for seeded taxonomy (+ any custom rows sharing these names)
UPDATE categories
SET emoji_icon = CASE name_en
  WHEN 'Beauty' THEN '💄'
  WHEN 'Electronics' THEN '💻'
  WHEN 'Fashion' THEN '👗'
  WHEN 'Home & Kitchen' THEN '🏠'
  WHEN 'Groceries' THEN '🛒'
  WHEN 'Sports & Outdoors' THEN '⚽'
  WHEN 'Baby & Kids' THEN '🍼'
  WHEN 'Automotive' THEN '🚗'
  WHEN 'Books & Stationery' THEN '📚'
  WHEN 'Pets' THEN '🐾'
  WHEN 'Cosmetics' THEN '✨'
  WHEN 'Pharmacy' THEN '💊'
  WHEN 'Personal Care' THEN '🛁'
  WHEN 'Fragrance' THEN '🌸'
  WHEN 'Hair Care' THEN '💇'
  WHEN 'Makeup' THEN '💄'
  WHEN 'Skincare' THEN '🧴'
  WHEN 'Nail Care' THEN '💅'
  WHEN 'Beauty Tools' THEN '🪞'
  WHEN 'Face' THEN '🙂'
  WHEN 'Eyes' THEN '👀'
  WHEN 'Lips' THEN '💋'
  WHEN 'Cheeks' THEN '😊'
  WHEN 'Makeup Sets' THEN '🎁'
  WHEN 'Cleansers' THEN '🧼'
  WHEN 'Toners' THEN '💧'
  WHEN 'Moisturizers' THEN '🧴'
  WHEN 'Serums & Treatments' THEN '🧪'
  WHEN 'Sunscreen' THEN '☀️'
  WHEN 'Masks' THEN '😷'
  WHEN 'Eye Care' THEN '👁️'
  WHEN 'Supplements' THEN '💊'
  WHEN 'OTC Medicine' THEN '💉'
  WHEN 'First Aid' THEN '🩹'
  WHEN 'Medical Devices' THEN '🩺'
  WHEN 'Vitamins' THEN '🍊'
  WHEN 'Minerals' THEN '🪨'
  WHEN 'Protein & Sports Nutrition' THEN '💪'
  WHEN 'Herbal Supplements' THEN '🌿'
  WHEN 'Bath & Body' THEN '🛁'
  WHEN 'Oral Care' THEN '🦷'
  WHEN 'Men''s Grooming' THEN '🧔'
  WHEN 'Feminine Care' THEN '♀️'
  WHEN 'Shower Gel' THEN '🚿'
  WHEN 'Body Lotion' THEN '🧴'
  WHEN 'Hand Care' THEN '🖐️'
  WHEN 'Deodorant' THEN '💨'
  WHEN 'Soap Bars' THEN '🧼'
  WHEN 'Shampoo' THEN '🫧'
  WHEN 'Conditioner' THEN '💆'
  WHEN 'Hair Treatments' THEN '✨'
  WHEN 'Hair Styling' THEN '💇'
  WHEN 'Hair Color' THEN '🎨'
  WHEN 'Women''s Fragrance' THEN '🌸'
  WHEN 'Men''s Fragrance' THEN '🪵'
  WHEN 'Unisex & Sets' THEN '🎁'
  WHEN 'Mobile & Tablets' THEN '📱'
  WHEN 'Computers' THEN '🖥️'
  WHEN 'TV & AV' THEN '📺'
  WHEN 'Audio' THEN '🎧'
  WHEN 'Cameras' THEN '📷'
  WHEN 'Wearables' THEN '⌚'
  WHEN 'Gaming' THEN '🎮'
  WHEN 'Accessories' THEN '🔌'
  WHEN 'Smartphones' THEN '📱'
  WHEN 'Tablets' THEN '📲'
  WHEN 'Feature Phones' THEN '☎️'
  WHEN 'Mobile Accessories' THEN '🔋'
  WHEN 'Laptops' THEN '💻'
  WHEN 'Desktops' THEN '🖥️'
  WHEN 'Monitors' THEN '🖥️'
  WHEN 'Storage & Drives' THEN '💾'
  WHEN 'PC Components' THEN '🧩'
  WHEN 'Televisions' THEN '📺'
  WHEN 'Streaming Devices' THEN '📡'
  WHEN 'Projectors' THEN '📽️'
  WHEN 'Headphones' THEN '🎧'
  WHEN 'Speakers' THEN '🔊'
  WHEN 'Home Theater' THEN '🎬'
  WHEN 'Consoles' THEN '🕹️'
  WHEN 'Games' THEN '👾'
  WHEN 'Gaming Accessories' THEN '🎛️'
  WHEN 'Chargers & Cables' THEN '🔌'
  WHEN 'Cases & Covers' THEN '📱'
  WHEN 'Power Banks' THEN '🔋'
  WHEN 'Screen Protectors' THEN '🛡️'
  WHEN 'CPUs' THEN '🧠'
  WHEN 'GPU' THEN '🖼️'
  WHEN 'RAM' THEN '📟'
  WHEN 'Motherboards' THEN '🧱'
  WHEN 'Women''s Clothing' THEN '👚'
  WHEN 'Men''s Clothing' THEN '👔'
  WHEN 'Shoes' THEN '👟'
  WHEN 'Bags & Luggage' THEN '👜'
  WHEN 'Watches & Jewelry' THEN '💎'
  WHEN 'Dresses' THEN '👗'
  WHEN 'Tops & Blouses' THEN '👚'
  WHEN 'Bottoms' THEN '👖'
  WHEN 'Outerwear' THEN '🧥'
  WHEN 'Activewear' THEN '🏃'
  WHEN 'Shirts & Polos' THEN '👔'
  WHEN 'T-Shirts' THEN '👕'
  WHEN 'Pants & Jeans' THEN '👖'
  WHEN 'Sneakers' THEN '👟'
  WHEN 'Sandals & Flip-Flops' THEN '🩴'
  WHEN 'Formal Shoes' THEN '👞'
  WHEN 'Boots' THEN '🥾'
  WHEN 'Handbags' THEN '👜'
  WHEN 'Backpacks' THEN '🎒'
  WHEN 'Travel Luggage' THEN '🧳'
  WHEN 'Belts' THEN '🪢'
  WHEN 'Hats & Caps' THEN '🧢'
  WHEN 'Scarves & Gloves' THEN '🧣'
  WHEN 'Sunglasses' THEN '🕶️'
  WHEN 'Kitchenware' THEN '🍳'
  WHEN 'Home Appliances' THEN '🔌'
  WHEN 'Furniture' THEN '🛋️'
  WHEN 'Bedding & Bath' THEN '🛏️'
  WHEN 'Home Decor' THEN '🖼️'
  WHEN 'Storage & Organization' THEN '📦'
  WHEN 'Cleaning Supplies' THEN '🧹'
  WHEN 'Cookware' THEN '🍳'
  WHEN 'Bakeware' THEN '🧁'
  WHEN 'Utensils & Gadgets' THEN '🥄'
  WHEN 'Dinnerware' THEN '🍽️'
  WHEN 'Drinkware' THEN '☕'
  WHEN 'Food Storage' THEN '🫙'
  WHEN 'Kitchen Appliances' THEN '🍲'
  WHEN 'Cleaning Appliances' THEN '🧹'
  WHEN 'Climate Control' THEN '❄️'
  WHEN 'Living Room' THEN '🛋️'
  WHEN 'Bedroom' THEN '🛏️'
  WHEN 'Office Furniture' THEN '🪑'
  WHEN 'Bed Linens' THEN '🛏️'
  WHEN 'Towels' THEN '🧺'
  WHEN 'Bathroom Accessories' THEN '🚽'
  WHEN 'Pots & Pans' THEN '🥘'
  WHEN 'Knife Sets' THEN '🔪'
  WHEN 'Cutting Boards' THEN '🪵'
  WHEN 'Blenders & Mixers' THEN '🥤'
  WHEN 'Rice Cookers' THEN '🍚'
  WHEN 'Coffee Makers' THEN '☕'
  WHEN 'Electric Kettles' THEN '🫖'
  WHEN 'Vacuum Cleaners' THEN '🧹'
  WHEN 'Irons & Steamers' THEN '♨️'
  WHEN 'Fresh Food' THEN '🥗'
  WHEN 'Pantry Staples' THEN '🧂'
  WHEN 'Beverages' THEN '🧃'
  WHEN 'Snacks & Sweets' THEN '🍪'
  WHEN 'Dairy & Eggs' THEN '🥛'
  WHEN 'Frozen' THEN '🧊'
  WHEN 'Fruits' THEN '🍎'
  WHEN 'Vegetables' THEN '🥦'
  WHEN 'Meat & Seafood' THEN '🥩'
  WHEN 'Rice & Grains' THEN '🌾'
  WHEN 'Oils & Sauces' THEN '🫒'
  WHEN 'Noodles & Pasta' THEN '🍜'
  WHEN 'Canned & Jarred' THEN '🥫'
  WHEN 'Spices & Seasonings' THEN '🌶️'
  WHEN 'Water & Soft Drinks' THEN '🥤'
  WHEN 'Tea & Coffee' THEN '🍵'
  WHEN 'Juice & Milk Alternatives' THEN '🧃'
  WHEN 'Chips & Crackers' THEN '🥨'
  WHEN 'Chocolate & Candy' THEN '🍫'
  WHEN 'Biscuits & Cookies' THEN '🍪'
  WHEN 'Chicken' THEN '🍗'
  WHEN 'Beef & Pork' THEN '🥩'
  WHEN 'Fish & Seafood' THEN '🐟'
  WHEN 'White Rice' THEN '🍚'
  WHEN 'Brown & Specialty Rice' THEN '🌾'
  WHEN 'Beans & Lentils' THEN '🫘'
  WHEN 'Exercise & Fitness' THEN '🏋️'
  WHEN 'Outdoor Recreation' THEN '🏕️'
  WHEN 'Team Sports' THEN '🏟️'
  WHEN 'Cycling' THEN '🚴'
  WHEN 'Water Sports' THEN '🏊'
  WHEN 'Cardio Equipment' THEN '🏃'
  WHEN 'Strength Training' THEN '🏋️'
  WHEN 'Yoga & Pilates' THEN '🧘'
  WHEN 'Camping & Hiking' THEN '⛺'
  WHEN 'Fishing' THEN '🎣'
  WHEN 'Football & Soccer' THEN '⚽'
  WHEN 'Basketball' THEN '🏀'
  WHEN 'Badminton & Tennis' THEN '🏸'
  WHEN 'Diapering' THEN '🧷'
  WHEN 'Feeding' THEN '🍼'
  WHEN 'Baby Care' THEN '👶'
  WHEN 'Toys' THEN '🧸'
  WHEN 'Kids Fashion' THEN '🧒'
  WHEN 'Nursery' THEN '🛏️'
  WHEN 'Diapers' THEN '🧷'
  WHEN 'Wipes' THEN '🧻'
  WHEN 'Formula & Baby Food' THEN '🍼'
  WHEN 'Bottles & Nursers' THEN '🍼'
  WHEN 'Bath & Skincare' THEN '🛁'
  WHEN 'Health & Safety' THEN '⛑️'
  WHEN 'Educational Toys' THEN '🧩'
  WHEN 'Outdoor Toys' THEN '🪁'
  WHEN 'Boys Clothing' THEN '👦'
  WHEN 'Girls Clothing' THEN '👧'
  WHEN 'Car Care' THEN '🧽'
  WHEN 'Oils & Fluids' THEN '🛢️'
  WHEN 'Exterior Accessories' THEN '🚦'
  WHEN 'Interior Accessories' THEN '🪑'
  WHEN 'Motorcycle' THEN '🏍️'
  WHEN 'Tools & Equipment' THEN '🔧'
  WHEN 'Wash & Wax' THEN '✨'
  WHEN 'Cleaning Kits' THEN '🧽'
  WHEN 'Engine Oil' THEN '🛢️'
  WHEN 'Coolant & Brake Fluid' THEN '💧'
  WHEN 'Helmets' THEN '⛑️'
  WHEN 'Motorcycle Parts' THEN '⚙️'
  WHEN 'Books' THEN '📖'
  WHEN 'School Supplies' THEN '✏️'
  WHEN 'Office Supplies' THEN '🖇️'
  WHEN 'Art & Craft' THEN '🎨'
  WHEN 'Fiction' THEN '📕'
  WHEN 'Non-Fiction' THEN '📘'
  WHEN 'Children''s Books' THEN '📗'
  WHEN 'Educational' THEN '📙'
  WHEN 'Notebooks' THEN '📓'
  WHEN 'Pens & Pencils' THEN '🖊️'
  WHEN 'Bags & Cases' THEN '🎒'
  WHEN 'Paper & Printing' THEN '📄'
  WHEN 'Desk Organizers' THEN '🗂️'
  WHEN 'Dog' THEN '🐶'
  WHEN 'Cat' THEN '🐱'
  WHEN 'Fish & Aquatics' THEN '🐠'
  WHEN 'Bird & Small Pets' THEN '🐦'
  WHEN 'Pet Health' THEN '🩺'
  WHEN 'Dog Food' THEN '🦴'
  WHEN 'Dog Treats & Toys' THEN '🎾'
  WHEN 'Dog Grooming' THEN '✂️'
  WHEN 'Cat Food' THEN '🐟'
  WHEN 'Litter & Accessories' THEN '📦'
  WHEN 'Cat Toys' THEN '🧶'
  WHEN 'Aquarium Supplies' THEN '🫧'
  WHEN 'Fish Food' THEN '🦐'
  ELSE emoji_icon
END
WHERE emoji_icon IS NULL
   OR btrim(emoji_icon) = ''
   OR emoji_icon = '🏷️';

-- Keyword fallback for any custom / unmatched rows still empty or tagged
UPDATE categories
SET emoji_icon = CASE
  WHEN name_en ILIKE '%water sport%' OR name_en ILIKE '%swim%' THEN '🏊'
  WHEN name_en ILIKE '%exercise%' OR name_en ILIKE '%fitness%' OR name_en ILIKE '%gym%' THEN '🏋️'
  WHEN name_en ILIKE '%yoga%' THEN '🧘'
  WHEN name_en ILIKE '%cycl%' OR name_en ILIKE '%bike%' THEN '🚴'
  WHEN name_en ILIKE '%camp%' OR name_en ILIKE '%hike%' THEN '⛺'
  WHEN name_en ILIKE '%fish%' THEN '🎣'
  WHEN name_en ILIKE '%beauty%' OR name_en ILIKE '%cosmetic%' OR name_en ILIKE '%makeup%' THEN '💄'
  WHEN name_en ILIKE '%phone%' OR name_en ILIKE '%mobile%' THEN '📱'
  WHEN name_en ILIKE '%computer%' OR name_en ILIKE '%laptop%' THEN '💻'
  WHEN name_en ILIKE '%shoe%' OR name_en ILIKE '%sneaker%' THEN '👟'
  WHEN name_en ILIKE '%kitchen%' OR name_en ILIKE '%cook%' THEN '🍳'
  WHEN name_en ILIKE '%grocery%' OR name_en ILIKE '%food%' THEN '🛒'
  WHEN name_en ILIKE '%baby%' OR name_en ILIKE '%kids%' OR name_en ILIKE '%child%' THEN '🍼'
  WHEN name_en ILIKE '%pet%' OR name_en ILIKE '%dog%' OR name_en ILIKE '%cat%' THEN '🐾'
  WHEN name_en ILIKE '%book%' THEN '📚'
  WHEN name_en ILIKE '%car%' OR name_en ILIKE '%auto%' OR name_en ILIKE '%motor%' THEN '🚗'
  WHEN name_en ILIKE '%sport%' THEN '⚽'
  WHEN name_en ILIKE '%home%' OR name_en ILIKE '%furniture%' THEN '🏠'
  WHEN name_en ILIKE '%fashion%' OR name_en ILIKE '%cloth%' THEN '👗'
  WHEN name_en ILIKE '%electronic%' THEN '💻'
  ELSE '📦'
END
WHERE emoji_icon IS NULL
   OR btrim(emoji_icon) = ''
   OR emoji_icon = '🏷️';

-- Trim whitespace before constraint
UPDATE categories
SET emoji_icon = btrim(emoji_icon)
WHERE emoji_icon IS NOT NULL AND emoji_icon <> btrim(emoji_icon);

COMMENT ON COLUMN categories.emoji_icon IS
  'Required emoji glyph for storefront category menus. Must be specific (generic 🏷️ not allowed).';

ALTER TABLE categories
  ALTER COLUMN emoji_icon SET NOT NULL;

ALTER TABLE categories
  DROP CONSTRAINT IF EXISTS categories_emoji_icon_required;

ALTER TABLE categories
  ADD CONSTRAINT categories_emoji_icon_required
  CHECK (length(btrim(emoji_icon)) > 0 AND emoji_icon <> '🏷️');
